### PR TITLE
getCharacteristics & getPrimaryServices

### LINKED ISSUE #7: .getCharacteristic(uuid) but unable to perform .getCharacteristics()
First of all, great browser thank you ! I need to use the function getCharacteristics() to get all the characteristic from a specified service. But only getCharacteristic is supported. 

- Any reason why this function isn't supported by the browser ? 
- Is the integration of this function plained to be release ? 

thanks

### LINKED ISSUE #20: Support .getPrimaryServices()
This is particularly useful for devices where you don't know the service UUID in advance.

### PR DESCRIPTION
**Pull request by boehlerlukas**
We implemented the `getCharacteristics` and `getPrimaryServices` BLE methods. I'm looking forward on your feedback.

Fixes #7 and fixes #20

Sponsored by Zemtu (https://www.zemtu.com/)

### CODE REVIEW

**Comment by daphtdazz** [comment]
Hi @boehlerlukas , thanks for submitting them and sorry for not spotting them earlier, I will try and get these merged or back to you if I have any questions asap.

**Comment by boehlerlukas** [comment]
Hey @daphtdazz ! Awesome, that would be phantastic!

**Comment by daphtdazz** [comment]
I've started having a look at this, but have run out of time today. Hopefully I will get some more time later this week...

**Comment by oclyke** [comment]
just tested this PR (though not extensively) and it worked like a charm. thank you SO MUCH @boehlerlukas I can't describe how much time this has saved me!

**Comment by boehlerlukas** [comment]
@oclyke great to hear that it helps :) All credits go to @googol7 at Zemtu (https://www.zemtu.com/)

**Comment by daphtdazz** [comment]
@boehlerlukas sorry I've been rubbish getting round to this. I've merged it, but might make a few tweaks (am going to try and sort out the `DEVELOPMENT_TEAM` thing so it doesn't change whenever anyone makes a new PR for example) before I release a new version of Webble. I also want to get some tests going!

**Comment by daphtdazz** [comment]
And also thank you very much for this PR!

**Pull request merged**
